# Generated by Django 4.0.3 on 2022-04-09 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_project_live_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.profile'),
        ),
    ]
