# Generated by Django 4.0.3 on 2022-04-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_project_user_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.URLField(blank=True),
        ),
    ]
