# Generated by Django 4.0.3 on 2022-04-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_project_live_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.URLField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.URLField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedln',
            field=models.URLField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True, max_length=150),
        ),
    ]
