# Generated by Django 4.0.3 on 2022-04-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_profile_facebook_alter_profile_instagram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='Creativity',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='creativty',
            new_name='creativity',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='Design',
            new_name='design',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='Usability',
            new_name='usability',
        ),
    ]
