# Generated by Django 4.0.3 on 2022-04-10 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_creativity_rating_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='post',
            new_name='project',
        ),
    ]
